apiVersion: apps/v1
kind: Deployment
metadata:
  name: shifthub-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shifthub-app
  template:
    metadata:
      labels:
        app: shifthub-app
    spec:
      containers:
      - name: shifthub-app
        image: docker.io/dmiov/shifthub-app:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: shifthub-app
spec:
  selector:
    app: shifthub-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: shifthub-app
spec:
  to:
    kind: Service
    name: shifthub-app
  port:
    targetPort: 8080