apiVersion: apps/v1
kind: Deployment
metadata:
  name: shifthub-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shifthub-api
  template:
    metadata:
      labels:
        app: shifthub-api
    spec:
      containers:
      - name: shifthub-api
        image: docker.io/dmiov/shifthub-api:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: shifthub-api
spec:
  selector:
    app: shifthub-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 5000
  type: ClusterIP
